# These are supported funding model platforms
github: [AvernusBot-MD]
patreon: # Replace 
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://github.com/WilsonOFC/AvernusBot-MD','https://github.com/glytglobal','https://dash.vortexuscloud.com/login', 'https://github.com/Arxeldev']
